networks:
  internal:

services:
  json-server:
    build:
      context: frontend
      dockerfile: json-server.dockerfile
    command: -h 0.0.0.0 -p 8000 /app/mock-db.json
    restart: unless-stopped
    volumes:
      - ./frontend/mock-db.json:/app/mock-db.json:ro
    ports:
      - 8000:8000
    networks:
      - internal

  frontend:
    build:
      context: frontend
      args:
        API_BASE: http://json-server:8000
        JSON_SERVER: 1
    restart: unless-stopped
    ports:
      - 3000:3000 
    networks:
      - internal
